name: npm-publish

#on:
#  push:
#    branches:
#      - main # Change this to your default branch

on:
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FIREBASE_PUBLIC_API_KEY: ${{ secrets.FIREBASE_PUBLIC_API_KEY_LIVE }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN_LIVE }}
      FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL_LIVE }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID_LIVE }}
      FIRSTORE_BUCKET_URL: ${{ secrets.FIRSTORE_BUCKET_URL_LIVE }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
      
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm install

      - run: git config --global user.name "microchipgnu"
      - run: git config --global user.email "microchipgnu@gmail.com"

      - run: npm version ${{ github.event.release.tag_name }}

      - run: npm run build && npm run dist

      # - run: npm test

      - run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_AUTH_TOKEN }}"


      - run: npm publish --tag ${{ github.event.release.target_commitish }}
        env:
          # Use a token to publish to NPM. See below for how to set it up
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      
      - run: git push
        env:
          # The secret is passed automatically. Nothing to configure.
          github-token: ${{ secrets.GITHUB_TOKEN }}